"""Candidate sites, runoff estimates and pond designs

Revision ID: 0007
Revises: 0006
Create Date: M5-14

Storage for the siting and design half of the pipeline. Three tables rather than
one wide one, because they answer different questions and change independently:

* `candidate_sites` -- *where*, decided by terrain and land availability.
* `runoffs` -- *how much water*, decided by rainfall and the curve number.
* `pond_designs` -- *what you build*, which depends on both and may be
  recomputed many times over one unchanged site.

As with 0005, nothing writes to these yet and that is deliberate: the contour
endpoints work with no database at all, and M6 is where persisted analyses are
orchestrated. A schema is cheaper waiting than added under a running feature.

Three columns exist because a stored number nobody can check is worse than no
stored number:

* `candidate_sites.criteria_breakdown` -- a score of 72 with no per-criterion
  contribution is unauditable, and being auditable is the whole point of an AHP
  model.
* `candidate_sites.analysis_tier` -- scores are not comparable across tiers, so
  the tier has to travel with the score.
* `runoffs.initial_abstraction_ratio` -- the 0.2S / 0.3S choice moves the annual
  total by about a fifth. CWC and IMD practice for India is 0.3S.

And `pond_designs.binding_constraint` is the column this migration is really
for. Depth, dimensions and cost are a calculator result; *which limit stopped the
design growing* is the planning recommendation, and it is the difference between
"build a 4.5 m pond" and "acquire more land, because the parcel is the limit".

The GiST indexes on the geometry columns are **not** created here. GeoAlchemy2
emits them itself as part of `create_table` when a `Geometry` column has
`spatial_index=True` (its default), so creating them again fails with
`DuplicateTable: relation "idx_candidate_sites_footprint" already exists` --
which is exactly what the autogenerated version of this file did. 0005 omits
them for the same reason.
"""

from __future__ import annotations

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.create_table(
        "candidate_sites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column("catchment_id", sa.UUID(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("suitability_score", sa.Float(), nullable=False),
        sa.Column("site_kind", sa.String(length=24), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "footprint",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("usable_area_m2", sa.Float(), nullable=True),
        sa.Column("mean_slope_pct", sa.Float(), nullable=True),
        sa.Column("depression_depth_m", sa.Float(), nullable=True),
        sa.Column("upstream_area_ha", sa.Float(), nullable=True),
        sa.Column("dominant_land_cover", sa.String(length=40), nullable=True),
        sa.Column("criteria_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("criteria_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analysis_tier", sa.String(length=24), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["catchment_id"], ["catchments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "rank", name="uq_candidate_sites_analysis_rank"),
    )
    op.create_index(
        op.f("ix_candidate_sites_analysis_id"), "candidate_sites", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_sites_catchment_id"), "candidate_sites", ["catchment_id"], unique=False
    )
    op.create_index(
        "ix_candidate_sites_score",
        "candidate_sites",
        ["analysis_id", "suitability_score"],
        unique=False,
    )
    op.create_table(
        "runoffs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column("catchment_id", sa.UUID(), nullable=True),
        sa.Column("catchment_area_ha", sa.Float(), nullable=False),
        sa.Column("composite_cn_amc2", sa.Float(), nullable=True),
        sa.Column("hydrologic_soil_group", sa.String(length=4), nullable=True),
        sa.Column("initial_abstraction_ratio", sa.Float(), nullable=True),
        sa.Column("annual_rainfall_mm", sa.Float(), nullable=True),
        sa.Column("annual_runoff_mm", sa.Float(), nullable=True),
        sa.Column("annual_runoff_m3", sa.Float(), nullable=True),
        sa.Column("runoff_coefficient", sa.Float(), nullable=True),
        sa.Column("dependable_75_runoff_m3", sa.Float(), nullable=True),
        sa.Column("monthly_runoff_mm", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rainfall_source", sa.String(length=40), nullable=True),
        sa.Column("rainfall_period_start", sa.Date(), nullable=True),
        sa.Column("rainfall_period_end", sa.Date(), nullable=True),
        sa.Column("cross_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["catchment_id"], ["catchments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runoffs_analysis_id"), "runoffs", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_runoffs_catchment_id"), "runoffs", ["catchment_id"], unique=False)
    op.create_table(
        "pond_designs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_site_id", sa.UUID(), nullable=True),
        sa.Column("runoff_id", sa.UUID(), nullable=True),
        sa.Column("depth_m", sa.Float(), nullable=False),
        sa.Column("top_length_m", sa.Float(), nullable=False),
        sa.Column("top_width_m", sa.Float(), nullable=False),
        sa.Column("bottom_length_m", sa.Float(), nullable=True),
        sa.Column("bottom_width_m", sa.Float(), nullable=True),
        sa.Column("side_slope", sa.Float(), nullable=True),
        sa.Column("gross_capacity_m3", sa.Float(), nullable=False),
        sa.Column("live_storage_m3", sa.Float(), nullable=True),
        sa.Column("dead_storage_m3", sa.Float(), nullable=True),
        sa.Column("excavation_volume_m3", sa.Float(), nullable=True),
        sa.Column("freeboard_m", sa.Float(), nullable=True),
        sa.Column("spillway_width_m", sa.Float(), nullable=True),
        sa.Column("estimated_cost_inr", sa.Float(), nullable=True),
        sa.Column("binding_constraint", sa.String(length=32), nullable=True),
        sa.Column("yield_capture_fraction", sa.Float(), nullable=True),
        sa.Column("stage_storage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "footprint",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_site_id"], ["candidate_sites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["runoff_id"], ["runoffs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pond_designs_binding_constraint"),
        "pond_designs",
        ["binding_constraint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pond_designs_candidate_site_id"),
        "pond_designs",
        ["candidate_site_id"],
        unique=False,
    )
    op.create_index(op.f("ix_pond_designs_runoff_id"), "pond_designs", ["runoff_id"], unique=False)


def downgrade() -> None:
    # Dropping the table takes its indexes with it, including the GiST ones
    # GeoAlchemy2 created.
    op.drop_table("pond_designs")
    op.drop_table("runoffs")
    op.drop_table("candidate_sites")
